#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libuninameslist
Version  : 20180701
Release  : 1
URL      : https://github.com/fontforge/libuninameslist/archive/20180701.tar.gz
Source0  : https://github.com/fontforge/libuninameslist/archive/20180701.tar.gz
Summary  : Unicode Names and Annotations List Library (NamesList.txt=@NL_VERSION@)
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: libuninameslist-lib
Requires: libuninameslist-license
BuildRequires : buildreq-distutils3
BuildRequires : sed

%description
LibUniNamesList
***************
LibUniNamesList holds www.unicode.org Nameslist.txt data which can be useful
for programs that need Unicode "Names", "Annotations" and block definitions.

%package dev
Summary: dev components for the libuninameslist package.
Group: Development
Requires: libuninameslist-lib = %{version}-%{release}
Provides: libuninameslist-devel = %{version}-%{release}

%description dev
dev components for the libuninameslist package.


%package lib
Summary: lib components for the libuninameslist package.
Group: Libraries
Requires: libuninameslist-license = %{version}-%{release}

%description lib
lib components for the libuninameslist package.


%package license
Summary: license components for the libuninameslist package.
Group: Default

%description license
license components for the libuninameslist package.


%prep
%setup -q -n libuninameslist-20180701

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537369182
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1537369182
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/libuninameslist
cp COPYING %{buildroot}/usr/share/doc/libuninameslist/COPYING
cp LICENSE %{buildroot}/usr/share/doc/libuninameslist/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libuninameslist.so
/usr/lib64/pkgconfig/libuninameslist.pc
/usr/share/man/man3/libuninameslist.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libuninameslist.so.1
/usr/lib64/libuninameslist.so.1.0.3

%files license
%defattr(-,root,root,-)
/usr/share/doc/libuninameslist/COPYING
/usr/share/doc/libuninameslist/LICENSE
