#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libuninameslist
Version  : 20190701
Release  : 3
URL      : https://github.com/fontforge/libuninameslist/archive/20190701/libuninameslist-20190701.tar.gz
Source0  : https://github.com/fontforge/libuninameslist/archive/20190701/libuninameslist-20190701.tar.gz
Summary  : Library with sparse array mapping for Unicode code points.
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: libuninameslist-lib = %{version}-%{release}
Requires: libuninameslist-license = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : sed

%description
libuninameslist – A Library of Unicode names and annotation data
================================================================
[![Build Status](https://travis-ci.org/fontforge/libuninameslist.svg?branch=master)](https://travis-ci.org/fontforge/libuninameslist) [![Build status](https://ci.appveyor.com/api/projects/status/qseac73evm9leu0g?svg=true)](https://ci.appveyor.com/project/fontforge/libuninameslist) [![Coverity Scan Build Status](https://scan.coverity.com/projects/793/badge.svg?flat=1)](https://scan.coverity.com/projects/793)

%package dev
Summary: dev components for the libuninameslist package.
Group: Development
Requires: libuninameslist-lib = %{version}-%{release}
Provides: libuninameslist-devel = %{version}-%{release}
Requires: libuninameslist = %{version}-%{release}
Requires: libuninameslist = %{version}-%{release}

%description dev
dev components for the libuninameslist package.


%package lib
Summary: lib components for the libuninameslist package.
Group: Libraries
Requires: libuninameslist-license = %{version}-%{release}

%description lib
lib components for the libuninameslist package.


%package license
Summary: license components for the libuninameslist package.
Group: Default

%description license
license components for the libuninameslist package.


%prep
%setup -q -n libuninameslist-20190701

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1562050618
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1562050618
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libuninameslist
cp COPYING %{buildroot}/usr/share/package-licenses/libuninameslist/COPYING
cp LICENSE %{buildroot}/usr/share/package-licenses/libuninameslist/LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libuninameslist.so
/usr/lib64/pkgconfig/libuninameslist.pc
/usr/share/man/man3/libuninameslist.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libuninameslist.so.1
/usr/lib64/libuninameslist.so.1.0.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libuninameslist/COPYING
/usr/share/package-licenses/libuninameslist/LICENSE
