#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libuninameslist
Version  : 20211114
Release  : 7
URL      : https://github.com/fontforge/libuninameslist/archive/20211114/libuninameslist-20211114.tar.gz
Source0  : https://github.com/fontforge/libuninameslist/archive/20211114/libuninameslist-20211114.tar.gz
Summary  : Unicode Names and Annotations List Library (NamesList.txt=@NL_VERSION@)
Group    : Development/Tools
License  : BSD-3-Clause GPL-2.0
Requires: libuninameslist-lib = %{version}-%{release}
Requires: libuninameslist-license = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : sed

%description
LibUniNamesList
***************
LibUniNamesList holds www.unicode.org Nameslist.txt data which can be useful
for programs that need Unicode "Names", "Annotations" and block definitions.

%package dev
Summary: dev components for the libuninameslist package.
Group: Development
Requires: libuninameslist-lib = %{version}-%{release}
Provides: libuninameslist-devel = %{version}-%{release}
Requires: libuninameslist = %{version}-%{release}

%description dev
dev components for the libuninameslist package.


%package lib
Summary: lib components for the libuninameslist package.
Group: Libraries
Requires: libuninameslist-license = %{version}-%{release}

%description lib
lib components for the libuninameslist package.


%package license
Summary: license components for the libuninameslist package.
Group: Default

%description license
license components for the libuninameslist package.


%prep
%setup -q -n libuninameslist-20211114
cd %{_builddir}/libuninameslist-20211114

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1636993431
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%reconfigure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1636993431
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libuninameslist
cp %{_builddir}/libuninameslist-20211114/COPYING %{buildroot}/usr/share/package-licenses/libuninameslist/e9cf76556aab3f1d3c2a70d8c96bceb4a681ebe3
cp %{_builddir}/libuninameslist-20211114/LICENSE %{buildroot}/usr/share/package-licenses/libuninameslist/4bc2eccad1f1ea956a58362d96c1f0d66c5fca06
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/uninameslist.h
/usr/lib64/libuninameslist.so
/usr/lib64/pkgconfig/libuninameslist.pc
/usr/share/man/man3/libuninameslist.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libuninameslist.so.1
/usr/lib64/libuninameslist.so.1.0.10

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libuninameslist/4bc2eccad1f1ea956a58362d96c1f0d66c5fca06
/usr/share/package-licenses/libuninameslist/e9cf76556aab3f1d3c2a70d8c96bceb4a681ebe3
